### ISSUE TITLE
Possible new Maintainer

### ISSUE THREAD

**Issue by SebastianAtWork** [johnfn/ts2gd#102]
Hi guys,
this project is really awesome and I am contemplating on helping out, since not much has happened in the last year.
2 Questions:
I work mainly on windows and the pr for that is still open. I tried the pr branch and it only compiles once. After that it says it compiles but not actually changes the gd file. The creator of that branch seems to be absent and hasn´t responded to an issue on his fork. Would you still accept PRs if I look this and fix it?
How feasible is it, to upgrade to godot 4.2 ? I know gdscript has gotten a lot of changes.

I know of the ECMAScript support repo, but I think the idea of generating gd script is way more useful than javascript. This project focuses on the type system that typescript provides, which has more value for me.

**Comment by fractaloutlook** [comment]
Heyo! 

I just today came across this googling for Godot and Typescript, as I'm trying to tie a browser-based client to a backend called SpacetimeDB, and they have a Typescript SDK.

I don't have answers to ANY of your questions there, as I'm brand new to Godot myself, but just wanted to comment here to let ya know that there is at least one human being still looking at this project. 👍

**Comment by johnfn** [comment]
Hey there! I unfortunately don't have the time to maintain this anymore myself, but I'm happy to appoint new maintainers if anyone wants to step up.

These days I use a lot of C#, which is good. Not quite as good as ts2gd 😉, but good.

**Comment by SebastianAtWork** [comment]
@johnfn Nice, thats good to know. How do you like C# in godot? Are you already working with 4.2?
C# in godot 3 was always very awkward to write. 
I will try to make it work under windows and make a new pr. Then I can at least play around with the new syntax and how much work it would be to change.

**Comment by AlexJWayne** [comment]
This project is neat and I’d be willing to help get things ready 4.2. However I’m still a noob with Godot, but pretty experienced in Typescript.

**Comment by SebastianAtWork** [comment]
Sorry, Unfortunately I don't have as much time as I thought. After the bit of research I could do, I think the existing pr is kind of close but it has so many other changes, that I cant really use that state. On a good sidenote, I think just using this in a docker devcontainer or something should make it runnable on windows. I will close this Issue as I dont have the time to update this to godot 4 currently. Everybody who searches this , look into hxgodot and haxe in general. Very typescript like but there is a somewhat maintained godot 4 repository.
