### ISSUE TITLE
invoked getters

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#11]
In typescript you can invoke a getter without parameters with parenthesis like `this.getter()` which will be translated to `this.getter()` in gdscript, but gdscript is not allowing this syntax for parameterless gets and needs `self.getter`

**Comment by johnfn** [comment]
Hmm can you give me a TS code example? I think I'm misunderstanding. Do you mean something [like this](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAu0DeAoaXoHN4oDMB7IgCgEo1NsaAnfAV1oDtoBWAbmqwF91voAWzABLZhSo0aSABYiIAOmJlyXGnx5A)? Or something else, like

**Comment by ksjogo** [comment]
Don't know what went wrong there, seems to work now.
