### ISSUE TITLE
generated code mixing tabs and spaces

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#12]
<img width="1348" alt="Screenshot 2021-11-15 at 00 21 59" src="https://user-images.githubusercontent.com/699858/141702741-5715fc1a-9b8b-4d24-a5c0-90e4e6f70c09.png">
Not sure what caused the mixing of spaces and tabs in the generated code.

**Comment by ksjogo** [comment]
Ran into further weirdness here, it seems related to the gd editor being open and changing things before run, will check.

**Comment by johnfn** [comment]
This usually happens to me if my project settings in Godot are set to use tabs rather than spaces - is that the case?
