### ISSUE TITLE
number types taken from value and not definition

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#17]
An instance variable of `passedTime: float = 0;`  will be generated as `var passedTime: int = 0`.

Changing to `passedTime: float = 0.0;` will generate `var passedTime: float = 0.0`.

Might there be some way to go from the float alias instead?

**Comment by johnfn** [comment]
Hmm, I think we should actually treat `passedTime: float = 0` as an error and suggest to change it to `0.0` if they want a `float`.

**Comment by johnfn** [comment]
Fixed with https://github.com/johnfn/ts2gd/commit/b0d36fe8648589261a50193a0bbebea62090a057
