### ISSUE TITLE
Exporting bit flags

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#20]
Would be great if
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html?highlight=exports#exporting-bit-flags
were supported. 
Might be easiest if we add a special decorator like @exports_flags(SomeEnum) and then iterate over that enum. 
I will look into that and might come back with more questions :D

**Comment by johnfn** [comment]
Oh this is neat! Should be an easy one. 

Also I read slightly below and learned that you can do `exports(Array, int)` which ts2gd doesn't support but it should be trivial to add, so why not add that too? :-)

**Comment by johnfn** [comment]
Partially fixed this with https://github.com/johnfn/ts2gd/commit/174ecf74c0957399a8b5ce0cab91c00dcd6903d2 - now you can do `@exports_flags("A", "B", "C")` 

Doing `@exports_flags(MyEnum)` is a little trickier because when the user saves that enum we'd have to recompile every file that depends on it...

**Comment by ksjogo** [comment]
Ahh, it seems there is some difference between latest and 3.4.
3.4 is this: https://docs.godotengine.org/en/3.4/getting_started/scripting/gdscript/gdscript_exports.html#exporting-bit-flags
I will change it to that.

Or is everything supposed to target 4?

**Comment by johnfn** [comment]
Oh, you're totally right. I must have opened the 4.0 docs by mistake, thanks for the catch.

**Comment by ksjogo** [comment]
Yeah, I linked those.
Supporting 4 will be interesting in the future, but I think we can skip that for now.

**Comment by johnfn** [comment]
Yeah. I'm really excited to target 4.0, but I personally probably won't add anything for that until we see at least a stable beta :)
