### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#23]
https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html
There would need to be some decorate or other flag to declare a file a tool file.
Adding 
```
//@ts-ignore
tool;
```
Can circumvent that for now, but doesn't put tool on top (is that required?).

**Comment by johnfn** [comment]
That's a really clever hack :-) Just added `@tool` support which should help: https://github.com/johnfn/ts2gd/commit/3a0f7c7b4c9f88bfcf6a6af22ace286542c45e0a
