### ISSUE TITLE
default arguments referencing previous arguments

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#27]
```
class Page extends Node2D {
  startWith(front: ImageTexture | null, back = front) {
   }
}
```
is valid typescript, but the generated gd isn't valid in 3.4:
```
# This file has been autogenerated by ts2gd. DO NOT EDIT!

extends Node2D

class_name Page
func startWith(front, _back= front):
  pass
```
with error `The identifier "front" isn't declared in the current scope.gdscript(-1)`

**Comment by johnfn** [comment]
Ahhh interesting. I guess we should just generate

```
func startWith(front, back):
  back = front

```

**Comment by ksjogo** [comment]
Yes, that should probably be the safest in regards to differing semantic

**Comment by johnfn** [comment]
Fixed with https://github.com/johnfn/ts2gd/commit/0196f01e51b671054b0745ff53d447c62d3b50e6
