### ISSUE TITLE
Warn if not exporting

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#35]
The code base works without adding `export` before class definitions if done consistently (nothing a module, all thus global scope).
But the get_node interface augmentation relies on things being modules.
Should we explicitly warn if we don't find exports?

**Comment by johnfn** [comment]
Yeah this is very reasonable. It's definitely an error not to export anything.

**Comment by johnfn** [comment]
Fixed with https://github.com/johnfn/ts2gd/commit/35de14b2b5101e1e78b4b15343bd0cdb79b4fdc2
