### ISSUE TITLE
NPM_TOKEN

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#36]
Current commits on main will fail due to the NPM_TOKEN not being set for the publish action:
https://github.com/marketplace/actions/npm-publish#github-action
https://github.com/johnfn/ts2gd/blob/main/.github/workflows/main.yml#L48
https://github.com/johnfn/ts2gd/runs/4303003005?check_suite_focus=true

After that one is added, it should auto publish when the version number is increased.

**Comment by johnfn** [comment]
Ah yea I'll have to do this later!

**Comment by johnfn** [comment]
Should be done.
