### ISSUE TITLE
| null types

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#5]
<img width="1178" alt="Screenshot 2021-11-13 at 22 12 31" src="https://user-images.githubusercontent.com/699858/141659231-31b91d6b-5479-42fa-a8cd-e2adb656968f.png">
It seems that member types with | null or optional get detected as null type only in the generated code.

**Comment by johnfn** [comment]
Ahh, this should be an easy fix! I'll put out a PR in a minute. 

Also, I should push a new version of ts2gd - I've actually made a lot of (good) changes since I last pushed 0.0.33 a while back.

**Comment by johnfn** [comment]
Fixed with https://github.com/johnfn/ts2gd/commit/31e71d50a77c221b459c8b6ac40618cf99ff8908

**Comment by ksjogo** [comment]
It seems to work with primitive types, but not with Nodes as far as I tried.

```  @exports
  frontTexture: ImageTexture | null;```
generates
```
export(null) var frontTexture
```

**Comment by johnfn** [comment]
@ksjogo should be fixed on master as well with https://github.com/johnfn/ts2gd/commit/8af918af74410a0d24d518ac4849e1c0f759de2f - but there's a long list of cases here and I don't use `@exports` in my own code, so let me know if there are any other edge cases I'm missing :)

**Comment by ksjogo** [comment]
I will try to add some more test cases. :)

How does it come that you are not using exports? Do you define values in code and not within the editor?

**Comment by johnfn** [comment]
Yeah, good question. I think I tend to want to live more in the IDE so I end up defining things directly in code rather than through exports.
