### ISSUE TITLE
test runner

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#6]
Heya,
looking through the code I was a bit surprised to not see a test runner like jest, but some manual running code 
https://github.com/johnfn/ts2gd/blob/d97c4c136c30dba63daa7f769f663b7548bfe4d6/tests/test.ts#L330
Is there a philosophical interest in keeping dev dependencies minimal or would you potenially be open to me adding a runner (to longterm make me safer in changing code by having jest in watch mode)?

**Comment by johnfn** [comment]
Honestly, there's no reason I'm not using Jest, that was a little silly of me :-) If you want to add it in, that would be awesome!

However I will say that I personally think the little test harness I have is pretty solid. If you run `npm run test` it'll drop you in the equivalent of a watch mode, automatically point you to failing tests, and run a nice diff on the expected output. Still, there's no reason you couldn't do that in Jest too :)

**Comment by ksjogo** [comment]
Yes, seems to work fine now. And less dependencies are easier to maintain, so let's keep it for now.
