### ISSUE TITLE
Template Args for get_node

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#7]
Is there some way to support
`this.get_node<AnimatedSprite>("somePath")` instead of `this.get_node("somePath") as AnimatedSprite`?

**Comment by johnfn** [comment]
Yep, we have `this.get_node_unsafe<T>` for that! 

THOUGH, I should mention that technically this.get_node() should be able to do everything you need - let me know about your specific cases and I can see if I can help you solve them in a more typesafe manner somehow!

**Comment by johnfn** [comment]
Actually I see what you mean - we could just combine these two together into get_node

**Comment by ksjogo** [comment]
Yes, especially as we transpile the _unsafe bit anyway.

**Comment by johnfn** [comment]
Fixed - added template args to `get_node` and deprecated `get_node_unsafe`.

**Comment by ksjogo** [comment]
How are these checks done for presence of a path?
On my project they seem to work well for load(paths), but I don't have completion on get_node.

**Comment by johnfn** [comment]
It's actually rather involved. Basically, ts2gd finds all instances of your node Node in your game, then for each of those instances it finds the set of all child paths on those nodes. Then it does the set intersection of those sets. So if one Node has a child "MyChild" but another Node instance does not, it won't autocomplete "MyChild".

Let me know if this isn't working for you though. It's certainly possible there are weird cases here.
