### ISSUE TITLE
bitwise operators

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#9]
It seems ts2gd isn't supporting bitwise operators yet (which can be commonly used for things like flags).

**Comment by ksjogo** [comment]
Collecting some info:
xor: unsure about precedence semantics https://github.com/godotengine/godot/issues/18816

**Comment by johnfn** [comment]
Oh, this should be super easy, it looks like they're all already implemented in GDScript, so the codegen should be really straightforward!

**Comment by johnfn** [comment]
Done here: https://github.com/johnfn/ts2gd/commit/1903b5fd4fd99739725d02c663c58dbd6bcbec97
