### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by igor875126** [johnfn/ts2gd#93]
Hey I really like your software,

I've already started a fresh project using `ts2gd`.

My question is, do you have any plans to develop the project ahead?

Best regards,
Igor

**Comment by johnfn** [comment]
Hi! I'm not dead, but I have been temporarily indisposed by work recently...

I don't really imagine the project is dead or anything. It's quite usable today, honestly! At least on macos... :P But yeah, I'm totally open to having other maintainers do some work while I'm busy.

**Comment by igor875126** [comment]
Hi! I'm very glad to hear that, thanks for your quick answer!
